param(
    [switch]$AllowDemoSecret
)
$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location $Root

$DemoSecret = "ListingTurbo-v1-offline-verifier-change-for-your-shop"
$LicenseSecret = $env:LISTINGTURBO_LICENSE_SECRET
if ([string]::IsNullOrWhiteSpace($LicenseSecret) -or $LicenseSecret -eq $DemoSecret) {
    if (-not $AllowDemoSecret) {
        throw "LISTINGTURBO_LICENSE_SECRET muss für Kundenbuilds auf ein eigenes Secret gesetzt sein. Für lokale Testpakete bewusst -AllowDemoSecret verwenden."
    }
    $LicenseSecret = $DemoSecret
    Write-Host "WARNUNG: Portable Paket wird mit öffentlichem Demo-Secret gebaut. Nicht an Kunden ausliefern." -ForegroundColor Yellow
}
$GeneratedSecretModule = Join-Path $Root "listingturbo\core\license_secret.py"
$SecretLiteral = $LicenseSecret.Replace("\", "\\").Replace("'", "\'")
Set-Content -LiteralPath $GeneratedSecretModule -Encoding UTF8 -Value @(
    "# Auto-generated by package_portable.ps1. Do not commit.",
    "LICENSE_VERIFY_SECRET = '$SecretLiteral'"
)

try {
Write-Host "[1/5] Native Backend bauen" -ForegroundColor Cyan
& "$Root\build_native.ps1"

Write-Host "[2/5] Python-Build-Umgebung vorbereiten" -ForegroundColor Cyan
if (!(Test-Path ".venv")) { py -3.12 -m venv .venv }
& ".\.venv\Scripts\python.exe" -m pip install --upgrade pip
& ".\.venv\Scripts\python.exe" -m pip install -r requirements.txt

Write-Host "[3/5] Tests ausführen" -ForegroundColor Cyan
& ".\.venv\Scripts\python.exe" run_tests.py

Write-Host "[4/5] PyInstaller EXE bauen" -ForegroundColor Cyan
Remove-Item ".\build" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item ".\dist" -Recurse -Force -ErrorAction SilentlyContinue
$addData1 = "listingturbo\data;listingturbo\data"
$addData2 = "examples;examples"
$addBinary = "native\bin\listingturbo_native.dll;native\bin"
$pyArgs = @(
    "-m", "PyInstaller",
    "--noconfirm",
    "--clean",
    "--windowed",
    "--name", "ListingTurboEnterprise",
    "--collect-all", "customtkinter",
    "--collect-all", "tkinterdnd2",
    "--hidden-import", "PIL._tkinter_finder",
    "--add-data", $addData1,
    "--add-data", $addData2
)
if (Test-Path ".\native\bin\listingturbo_native.dll") { $pyArgs += @("--add-binary", $addBinary) }
$pyArgs += "app.py"
& ".\.venv\Scripts\python.exe" @pyArgs

Write-Host "[5/5] Portable Paket schreiben" -ForegroundColor Cyan
$Portable = ".\dist\ListingTurboPortable"
Remove-Item $Portable -Recurse -Force -ErrorAction SilentlyContinue
New-Item -ItemType Directory -Force $Portable | Out-Null
Copy-Item ".\dist\ListingTurboEnterprise\*" $Portable -Recurse -Force
Copy-Item ".\README.md", ".\CHANGELOG.md", ".\VERIFY_NATIVE.md" $Portable -Force
Compress-Archive -Path "$Portable\*" -DestinationPath ".\dist\ListingTurboEnterprise_Portable.zip" -Force
Write-Host "Portable EXE: $Root\dist\ListingTurboPortable\ListingTurboEnterprise.exe" -ForegroundColor Green
Write-Host "Portable ZIP: $Root\dist\ListingTurboEnterprise_Portable.zip" -ForegroundColor Green
} finally {
    Remove-Item $GeneratedSecretModule -Force -ErrorAction SilentlyContinue
}
